### ISSUE TITLE
Corrigir importação dos forums

### ISSUE THREAD

**Issue by brunosmartin** [hacklabr/paralapraca#86]
(timtec) bruno@angola  ~/devel/timtec   paralapraca ●  ./manage.py import_forum_moodle moodle/mdl_forum_discussions.csv moodle/mdl_forum_posts.csv
Raven is not configured (logging is disabled). Please see the documentation for more information.
. . . . . . .
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/bruno/.virtualenvs/timtec/lib/python2.7/site-packages/django/core/management/**init**.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/bruno/.virtualenvs/timtec/lib/python2.7/site-packages/django/core/management/**init**.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/bruno/.virtualenvs/timtec/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/home/bruno/.virtualenvs/timtec/lib/python2.7/site-packages/raven/contrib/django/management/**init**.py", line 41, in new_execute
    return original_func(self, _args, *_kwargs)
  File "/home/bruno/.virtualenvs/timtec/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(_args, *_options)
  File "/home/bruno/.virtualenvs/timtec/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(_args, *_kwargs)
  File "/home/bruno/devel/paralapraca/paralapraca/management/commands/import_forum_moodle.py", line 267, in handle
    forum=destination['forum'],
TypeError: 'NoneType' object has no attribute '**getitem**'
(timtec) ✘ bruno@angola  ~/devel/timtec   paralapraca ● 

**Comment by laurybueno** [comment]
Corrigido em 7c6ddb614e6e898b6d25b862cea8e593fb99d17b
